process:
  name: "stream"
  topic_name: "its-stream"
  script_path: "proc/proc_stream.go"
  data_path: "data/archive" // proc_stream에서 압축이 필요한 경우 해당 파일에 imglog 를 기술한다. proc_archive 는 파일을 주기적으로 확인하고 삭제한다.
